Transform: AWS::Serverless-2016-10-31
Resources:
  VaccineTweeter:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: vaccine-bot
      CodeUri: ./vaccine-bot
      Events:
        CWCron:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
            Name: VaccineTwitterBot
            Description: Daily event for Vaccine Twitter art bot
            Enabled: True
      Environment:
        Variables:
          TWITTER_CONSUMER_KEY: '{{resolve:secretsmanager:/vaccine-bot/twitter-secrets:SecretString:TwitterConsumerKey}}'
          TWITTER_CONSUMER_SECRET: '{{resolve:secretsmanager:/vaccine-bot/twitter-secrets:SecretString:TwitterConsumerSecret}}'
          TWITTER_ACCESS_TOKEN: '{{resolve:secretsmanager:/vaccine-bot/twitter-secrets:SecretString:TwitterAccessToken}}'
          TWITTER_ACCESS_SECRET: '{{resolve:secretsmanager:/vaccine-bot/twitter-secrets:SecretString:TwitterAccessSecret}}'
    Metadata:
      BuildMethod: makefile