Transform: AWS::Serverless-2016-10-31
Parameters:
  ConsumerKey:
    Type: String
    NoEcho: True
    Description: Consumer Key for accessing the Twitter API
  ConsumerSecret:
    Type: String
    NoEcho: True
    Description: Consumer Secret for accessing the Twitter API
  AccessToken:
    Type: String
    NoEcho: True
    Description: Access Token for accessing the Twitter API
  AccessSecret:
    Type: String
    NoEcho: True
    Description: Access Secret for accessing the Twitter API
Resources:
  VaccineTweeter:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: vaccine-bot
      CodeUri: ./vaccine-bot
      Events:
        CWCron:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
            Name: VaccineTwitterBot
            Description: Daily event for Vaccine Twitter art bot
            Enabled: True
      Environment:
        Variables:
          TWITTER_CONSUMER_KEY:
            Ref: ConsumerKey
          TWITTER_CONSUMER_SECRET:
            Ref: ConsumerSecret
          TWITTER_ACCESS_TOKEN:
            Ref: AccessToken
          TWITTER_ACCESS_SECRET:
            Ref: AccessSecret
    Metadata:
      BuildMethod: makefile