name: Build
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md

jobs:
  test:
    name: Test code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.6'
      - name: Download dependencies
        run: go get -d -v ./vaccine-bot
      - name: Running unit tests
        run: go test -v ./vaccine-bot
  
  deploy:
    name: Build and deploy artifact
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.6'
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          role-duration-seconds: 3000
      - name: Updating Secrets Manager secret value
        env:
          TWITTER_SECRET: ${{ secrets.TWITTER_SECRET_OBJECT }}
        run: .github/scripts/update_secret.sh
      - name: Building lambda deployment package
        run: sam build
      - name: Deploying lambda
        env:
          DEPLOY_BUCKET: ${{ secrets.SAM_ARTIFACT_BUCKET }}
        run: sam deploy --s3-bucket "$DEPLOY_BUCKET" --capabilities CAPABILITY_IAM --stack-name vaccine-bot --no-fail-on-empty-changeset