name: Build
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md

jobs:
  test:
    name: Test code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.6'
      - name: Download dependencies
        run: go get -d -v ./vaccine-bot
      - name: Running unit tests
        run: go test -v ./vaccine-bot
  
  deploy:
    name: Build and deploy artifact
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.6'
      - name: Building lambda deployment package
        run: sam build
